% set name = "borgbackup" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/borgbackup-{{ version }}.tar.gz
  sha256: d730687443f1beb602b1d72bae36318f6f9654818fcdc50458540ec579e57260

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python >=3.8
    - setuptools
    - pkgconfig
    - cython
    - setuptools_scm >=1.7
  host:
    - python >=3.8
    - pkgconfig
    - cython
    - pip
  run:
    - python >=3.8
    - openssl >=1.0.0
    - libacl

test:
  imports:
    - borgbackup
  commands:
    - pip check
    - flake8 src scripts conftest.py
  requires:
    - pip
    - flake8

about:
  home: https://borgbackup.readthedocs.io/
  summary: Deduplicated, encrypted, authenticated and compressed backups
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giuliocentorame
